services:

  webui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - 3000:8080

    environment:
      SEARXNG_URL: http://searxng:8080
      ENABLE_RAG_WEB_SEARCH: True
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 4
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 12
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"
      # SEARXNG_QUERY_URL: http://searxng.local/search?q=<query>

    volumes:
      - open-webui:/app/backend/data
    depends_on:
     - searxng
    restart: always
    networks:
      - web

  searxng:
    image: searxng/searxng:latest
    ports:
      - '8080:8080'
    networks:
      - web
    volumes:
      - searxng:/etc/searxng
    # environment:
    #   - 'INSTANCE_NAME=searxng-in'
    restart: always

volumes:
  open-webui: {}
  searxng: {}

networks:
  web: