server:
  secret_key: '319677123456789'  # Replace with a strong, random string
  base_url: "http://searxng:8088/"
  enable_http_api: True
  bind_address: "0.0.0.0"
  port: 8088
  # Uncomment the following line if CSRF protection is causing issues
  # csrf: False
  # allowed_hosts:
  #   - '*'

ui:
  theme: oscar

general:
  public: True  # Allows access without authentication

search:
  safe_search: 0
  autocomplete: ""
  default_lang: ""
  formats:
    - html
    - json